/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/waiting': typeof WaitingRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/waiting': typeof WaitingRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/waiting': typeof WaitingRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/settings'
    | '/waiting'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/github/connect'
    | '/api/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/members'
    | '/settings'
    | '/waiting'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/github/connect'
    | '/api/github/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/members'
    | '/settings'
    | '/waiting'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/github/connect'
    | '/api/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  SettingsRoute: typeof SettingsRoute
  WaitingRoute: typeof WaitingRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  SettingsRoute: SettingsRoute,
  WaitingRoute: WaitingRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
